version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=https://твой-домен.render.com

  frontend:
    build: ./frontend  
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://твой-домен.render.com
    depends_on:
      - backend